# Generated by Django 5.1.15 on 2026-09-28 20:00

import django_multitenant.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity_logs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='activitylog',
            managers=[
                ('objects', django_multitenant.models.TenantManager()),
            ],
        ),
    ]
