# Generated by Django 5.1.15 on 2026-09-29 03:43

import apps.companies.models
import apps.companies.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=apps.companies.models.company_logo_upload_path, validators=[apps.companies.validators.validate_company_logo]),
        ),
    ]
