# Generated by Django 5.1.15 on 2026-09-29 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='subscription_plan',
            field=models.CharField(choices=[('Basic', 'Basic'), ('Pro', 'Pro')], db_index=True, default='Basic', max_length=20),
        ),
    ]
